spawn_points:
  - id: 1
    name: "P1"
    coordinates:
      x: 170.0
      y: 19.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 2
    name: "P2"
    coordinates:
      x: 260.0
      y: 19.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 3
    name: "P3"
    coordinates:
      x: 380.0
      y: 19.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 4
    name: "P4"
    coordinates:
      x: 515.0
      y: 19.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 5
    name: "P5"
    coordinates:
      x: 585.0
      y: 90.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 6
    name: "P6"
    coordinates:
      x: 380.0
      y: 122.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 7
    name: "P7"
    coordinates:
      x: 255.0
      y: 122.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 8
    name: "P8"
    coordinates:
      x: 170.0
      y: 122.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 9
    name: "P9"
    coordinates:
      x: 80.0
      y: 122.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 10
    name: "P10"
    coordinates:
      x: 28.0
      y: 218.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 11
    name: "P11"
    coordinates:
      x: 585.0
      y: 178.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 12
    name: "P12"
    coordinates:
      x: 510.0
      y: 223.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 13
    name: "P13"
    coordinates:
      x: 303.0
      y: 175.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 14
    name: "P14"
    coordinates:
      x: 184.0
      y: 242.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 15
    name: "P15"
    coordinates:
      x: 178.0
      y: 317.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 16
    name: "P16"
    coordinates:
      x: 135.0
      y: 196.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 17
    name: "P17"
    coordinates:
      x: 585.0
      y: 325.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 18
    name: "P18"
    coordinates:
      x: 510.0
      y: 283.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 19
    name: "P19"
    coordinates:
      x: 576.0
      y: 455.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 20
    name: "P20"
    coordinates:
      x: 525.0
      y: 392.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 21
    name: "P21"
    coordinates:
      x: 452.0
      y: 360.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 22
    name: "P22"
    coordinates:
      x: 435.0
      y: 223.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

  - id: 23
    name: "P23"
    coordinates:
      x: 28.0
      y: 400.0
    active: true
    fare_type_bias:
      STANDARD: 0.3
      SPECIAL: 0.7

 