# Team Names Database
teams:
  - Aylesbury 1
  - Aylesbury 2
  - Aylesbury 3
  - Aylesbury 4
  - Aylesbury 5
  - Aylesbury 6
  - Aylesbury 7
  - Aylesbury 8
  - Aylesbury 9
  - Aylesbury 10
  - Aylesbury 11
  - Aylesbury 12
  - Aylesbury 13
  - Aylesbury 14
  - Blekinge 1
  - Blekinge 2
  - Blekinge 3
  - Blekinge 4
  - Blekinge 5
  - Blekinge 6
  - Blekinge 7
  - Blekinge 8
  - Blekinge 9
  - Blekinge 10
  - Blekinge 11
  - Blekinge 12
  - Blekinge 13
  - Blekinge 14
  - Crested 1
  - Crested 2
  - Crested 3
  - Crested 4
  - Crested 5
  - Crested 6
  - Crested 7
  - Crested 8
  - Crested 9
  - Crested 10
  - Crested 11
  - Crested 12
  - Crested 13
  - Crested 14
  - Duclair 1
  - Duclair 2
  - Duclair 3
  - Duclair 4
  - Duclair 5
  - Duclair 6
  - Duclair 7
  - Duclair 8
  - Duclair 9
  - Duclair 10
  - Duclair 11
  - Duclair 12
  - Duclair 13
  - Duclair 14